### ISSUE TITLE
Thread safety of GitHub::Result.error(e)

### ISSUE THREAD

**Issue by KelseyDH** [github/github-ds#18]
Has this library been checked for thread safety? (in particular, for MRI ruby)

E.g. when looking at [`GitHub::Result.error(e)`](https://github.com/github/github-ds/blob/master/lib/github/result.rb#L225) I noticed it appears to be setting an instance variable within a class method:

```ruby
def self.error(e)
  result = allocate
  result.instance_variable_set(:@error, e)
  result
 end
```

Setting instance variable within a class method is not thread safe, though I'm sure whether that also applies to using `instance_variable_set(:@error, e)` within a class method as you're doing so here.  Any thoughts?

**Comment by jnunemaker** [comment]
We don't currently do anything threaded, so we haven't explicitly checked the library for thread-safety. That said, most of this should be fine. Sharing a `GitHub::SQL` instance across threads likely isn't, but since most of this is built on top of ActiveRecord for the actual connection/query part, AR's connection pool should make the execution of things safe. 

I'm not really sure why anyone would build up an instance in one thread and execute it in another though. I would stick to using a `GitHub::SQL` instance in a single thread and you'll be fine. If you have any specific questions/examples, I'd be happy to take a look.

A quick scan of `GitHub::Result` looks clean. GitHub::KV builds on Result and SQL and a quick scan of it looks fine too. Hope that quick summary is helpful.

> Setting instance variable within a class method is not thread safe, though I'm sure whether that also applies to using instance_variable_set(:@error, e) within a class method as you're doing so here. 

I don't believe this use is unsafe for threads, but I am far from a thread/concurrency mastermind 😄 . Each invocation returns a new instance so nothing would be shared. Happy to be wrong if anyone watching knows otherwise.

Closing the issue to keep things tidy, but please feel free to ask more questions.

**Comment by KelseyDH** [comment]
Thanks for the response, this article has good details on ruby threadsafety which makes me believe that the error instance variable set here is not thread safe as a class method:  https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/

It appears a little refactoring of this method to initialize a new result could make it so.  That every Result object call is to a new one definitely complicates testing around this also.  Any insights welcome!
